# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 03:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login', '0003_auto_20160905_0043'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poke',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('userpoked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokesreceived', to='login.User')),
                ('userpoking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokesmade', to='login.User')),
            ],
            options={
                'ordering': ['count'],
            },
        ),
    ]
