# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-05 04:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_auto_20160823_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='description',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_level',
        ),
    ]
